### PR TITLE
register page changes-Tarak

### PR DESCRIPTION
**Pull request by Tarak1246**
1. Handled all form field validations and corresponding UI changes
2. Added a clear button and its functionality

### CODE REVIEW

**Comment by Tarak1246** [comment]
no conflicts..here closed the pull request

**Review by Tarak1246 — COMMENTED** [review]
No errors

**Review by prasannayekkaladevi — COMMENTED** [review]
The code runs successfully

**Comment by prasannayekkaladevi** [comment]
Reviewed and closed the issue

**Pull request merged**
